Made changes according to the review
spaceuptech/galaxy-runtimes pull request #2
Opened 2020-01-08 07:04 UTC by suyash16999

2020-01-08 11:51 UTC, YourTechBud requested changes

2020-01-08 11:51 UTC, YourTechBud commented on builder/node-10/run.sh
> +rm package-lock.json
Remove this

2020-01-08 11:51 UTC, YourTechBud commented on runtime/python-3.7/run.sh
> +curl -O -L $URL/v1/api/test/files/build.zip
You are forgetting adding the token here

2020-01-18 07:03 UTC, sharadregoti approved these changes

2020-01-18 07:04 UTC, merged